# Generated by Django 3.2.3 on 2021-05-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20210516_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.village', verbose_name='Municipality / Village'),
        ),
    ]
