# Generated by Django 3.2.3 on 2021-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_area_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultsettings',
            name='expire_orders_in',
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='average_weight_of_normal_item',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='average_weight_of_normal_item in grams'),
        ),
        migrations.AlterField(
            model_name='defaultsettings',
            name='normal_order_weight_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='normal_order_weight_limit in Kgs'),
        ),
    ]
