# Generated by Django 3.2.3 on 2021-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20210517_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsettings',
            name='expire_orders_in',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='expire_orders_in hrs'),
        ),
    ]
