# Generated by Django 3.2.3 on 2021-05-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_defaultsettings_expire_orders_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
