# Generated by Django 3.2.3 on 2021-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_business_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
