# Generated by Django 3.2.3 on 2021-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_units_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
