# Generated by Django 3.2.3 on 2021-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20210519_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
