# Generated by Django 3.2.3 on 2021-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20210519_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
