# Generated by Django 3.2.3 on 2021-05-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='Banner')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='credit_users',
            field=models.ManyToManyField(blank=True, to='src.CommonUser'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_accept_credit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='Store Category'),
        ),
    ]
