# Generated by Django 3.2.3 on 2021-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20210527_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='QR Code'),
        ),
    ]
