# Generated by Django 3.2.3 on 2021-05-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_auto_20210531_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ManyToManyField(blank=True, to='src.OrderDetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_list_image',
            field=models.ImageField(blank=True, null=True, upload_to='Order'),
        ),
    ]
