# Generated by Django 3.2.3 on 2021-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_auto_20210531_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_confirmed',
            new_name='is_confirmed_by_user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_pickup',
            new_name='is_packing_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='is_pickup_by_agent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_processed_by_business',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
