# Generated by Django 3.2.3 on 2021-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20210601_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
