# Generated by Django 3.2.3 on 2021-06-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_orderdetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_item_not_available',
            field=models.ManyToManyField(blank=True, related_name='order_item_not_available', to='src.OrderDetails'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.ManyToManyField(blank=True, related_name='order_details', to='src.OrderDetails'),
        ),
    ]
