# Generated by Django 3.2.3 on 2021-06-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_auto_20210604_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_placed_by_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
