# Generated by Django 3.2.3 on 2021-06-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_auto_20210605_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed_by_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_packing_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_pickup_by_agent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_placed_by_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_processed_by_business',
        ),
    ]
