# Generated by Django 3.2.3 on 2021-06-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0028_orderdelivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagentnotification',
            name='order',
        ),
        migrations.AddField(
            model_name='deliveryagentnotification',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.orderdelivery'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
