# Generated by Django 3.2.3 on 2021-06-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_auto_20210611_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='area_specified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.area'),
        ),
    ]
