# Generated by Django 3.2.3 on 2021-06-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_orderdelivery_area_specified'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='picked_orders',
            field=models.ManyToManyField(blank=True, related_name='picked_orders', to='src.Order'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders_available', to='src.Order'),
        ),
    ]
