# Generated by Django 3.2.3 on 2021-06-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0032_alter_orderdelivery_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='total_user_orders_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.orderdelivery'),
        ),
    ]
