# Generated by Django 3.2.3 on 2021-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0033_auto_20210611_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_upi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
