# Generated by Django 3.2.3 on 2021-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0035_order_order_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_bill',
            field=models.ImageField(blank=True, null=True, upload_to='Order Bill'),
        ),
    ]
