# Generated by Django 3.2.3 on 2021-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0036_order_order_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='is_manager',
        ),
        migrations.RemoveField(
            model_name='commonuser',
            name='user',
        ),
        migrations.AddField(
            model_name='business',
            name='account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
