# Generated by Django 3.2.3 on 2021-06-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0038_securityquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='security_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.securityquestions'),
        ),
    ]
