# Generated by Django 3.2.3 on 2021-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0039_auto_20210617_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fcm_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='businessnotification',
            name='header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessnotification',
            name='is_send',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='businessnotification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='fcm_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='fcm_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentnotification',
            name='header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentnotification',
            name='is_send',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentnotification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='is_send',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
