# Generated by Django 3.2.3 on 2021-08-03 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0040_auto_20210626_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payment_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='defaultsettings',
            name='minimum_order_amount_in_a_day_for_a_user',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='payment_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='BusinessTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('platform_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.business')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.order')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('pay_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.business')),
                ('transactions', models.ManyToManyField(blank=True, to='src.BusinessTransactions')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=25, null=True)),
                ('is_cod', models.BooleanField(blank=True, default=False, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('platform_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_order_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('gross_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('delivery_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.deliveryagent')),
                ('delivery_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.orderdelivery')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_debit', models.BooleanField(blank=True, default=False, null=True)),
                ('is_credit', models.BooleanField(blank=True, default=False, null=True)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('pay_by', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.deliveryagent')),
                ('transactions', models.ManyToManyField(blank=True, to='src.AgentTransactions')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.FloatField(blank=True, default=0.0, null=True)),
                ('current_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_business_commission_credited', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_delivery_commission_credited', models.FloatField(blank=True, default=0.0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
